[package]
name = "suins_auction"
edition = "2024.beta"

[dependencies]
suins = { local = "../suins" }
seal = { git = "git@github.com:MystenLabs/seal.git", subdir = "move/seal", rev = "3eae7967484e631d07dfced2b541330949bf21dc" }

# To resolve a version conflict and force a specific version for dependency
# override use `override = true`
# Override = { local = "../conflicting/version", override = true }

[addresses]
suins_auction = "0x1" # For tests to not conflict with 0x0 address of suins.
package_id_check = "0x1" # Used for seal package id check. After deploying the initial contract this should be updated with the correct package id and a new version needs to be published
